//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent.Core.Concrete.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rent.Core.Concrete.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikleri kaydetmek istiyor musunuz?.
        /// </summary>
        public static string CloseCancelFormWarning {
            get {
                return ResourceManager.GetString("CloseCancelFormWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçmiş olduğunuz bilgiler silinecektir, Devam etmek istiyor mu sunuz ?.
        /// </summary>
        public static string DeleteContinue {
            get {
                return ResourceManager.GetString("DeleteContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Silme İşlemi.
        /// </summary>
        public static string DeleteRecordWarning {
            get {
                return ResourceManager.GetString("DeleteRecordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulmuş olan satırlar silinecektir !!!  Devam etmek istiyor mu sunuz ?.
        /// </summary>
        public static string DeleteRows {
            get {
                return ResourceManager.GetString("DeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mükerrer veri girişi!!!.
        /// </summary>
        public static string DuplicateDataMessage {
            get {
                return ResourceManager.GetString("DuplicateDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata!!!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya aktarımı.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyayı açmak istiyor musunuz?.
        /// </summary>
        public static string ExportFileOpen {
            get {
                return ResourceManager.GetString("ExportFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string ExportPdf {
            get {
                return ResourceManager.GetString("ExportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xls.
        /// </summary>
        public static string ExportXls {
            get {
                return ResourceManager.GetString("ExportXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xlsx.
        /// </summary>
        public static string ExportXlsx {
            get {
                return ResourceManager.GetString("ExportXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı kullanıcı adı yada parola!!!.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF dosya (*.pdf)|*.pdf.
        /// </summary>
        public static string PDFOpenFileFilter {
            get {
                return ResourceManager.GetString("PDFOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Numaraları.
        /// </summary>
        public static string RowNumbers {
            get {
                return ResourceManager.GetString("RowNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0&apos;dan küçük yada eşit olamaz!.
        /// </summary>
        public static string RuleGreaterOrEqualZeroWarning {
            get {
                return ResourceManager.GetString("RuleGreaterOrEqualZeroWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş bırakılamaz!.
        /// </summary>
        public static string RuleIsNotBlankWarning {
            get {
                return ResourceManager.GetString("RuleIsNotBlankWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydediliyor!!!.
        /// </summary>
        public static string SavingProcess {
            get {
                return ResourceManager.GetString("SavingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Kayıtlar.
        /// </summary>
        public static string ShowActiveRecords {
            get {
                return ResourceManager.GetString("ShowActiveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kayıtlar.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resmi göster.
        /// </summary>
        public static string ShowImage {
            get {
                return ResourceManager.GetString("ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydetme işlemi tamamlandı.
        /// </summary>
        public static string SuccessfulSaveMessage {
            get {
                return ResourceManager.GetString("SuccessfulSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bilgilerinizi kontrol ediniz!!.
        /// </summary>
        public static string ValidateErrorString {
            get {
                return ResourceManager.GetString("ValidateErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı!!!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLS dosya (*.xls)|*.xls.
        /// </summary>
        public static string XLSOpenFileFilter {
            get {
                return ResourceManager.GetString("XLSOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLSX dosya (*.xlsx)|*.xlsx.
        /// </summary>
        public static string XLSXOpenFileFilter {
            get {
                return ResourceManager.GetString("XLSXOpenFileFilter", resourceCulture);
            }
        }
    }
}
